#!/bin/bash

#
# (G)it (do): [-p] ["message" | "--"] targets...
#


_gido() {

    if [ -z "$1" ]; then
        echo "Status:" 
        git status
    else
        echo "Modify:"
        local push=-
        local target=-
        local message=-
        
        if [ "$1" == "-p" ]; then
            push="-p"
            shift
        fi

        message="$1"
        if [ "$message" == "--" ]; then
            message="Various unremarkable details"
        fi
        shift
        echo "-m '$message'"
        echo "add $@"

        if [ -n "$1" ]; then 
            for target in "$@"; do

                git add "$target"
            done
            git commit -m "$message"


        fi
        
        if [ "$push" == "-p" ]; then
            git push origin master
        fi
    fi
}

_gido "$@"
